version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=sua_chave_secreta_jwt_aqui
      - JWT_EXPIRES_IN=7d
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Pega do .env local ou do Dokploy
      - CORS_ORIGIN=*
      - BCRYPT_SALT_ROUNDS=10
    volumes:
      - sqlite_data:/app/prisma

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL:-http://api.193.122.213.155.nip.io/api} # Injeta a URL no build
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  sqlite_data:
